config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :campuses
  resources :reservations
  resources :users
  resources :features

  root 'welcome#index'

  resources :conf_rooms do
    collection do
      post "search"
    end
  end

  post "signin", to: "welcome#signin"
  delete "signout", to: "welcome#signout"

  get "signups", to: "signups#index"
  post "signups", to: "signups#signup"
  get 'tiy_rooms/index'

  get "reservations", to: "reservations#index"

end

app/models/conf_room.rb
# == Schema Information
#
# Table name: conf_rooms
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  location    :string(255)
#  sq_feet     :integer
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  pic         :string(255)
#  campus_id   :integer
#  user        :reference
#  user_id     :integer
#

class ConfRoom < ActiveRecord::Base
  validates :name, presence: true
  validates :campus_id, presence: true


  belongs_to :campus


  has_many :reservations

  has_many :conference_room_features
  has_many :features, through: :conference_room_features


  scope :for_user, ->(user) { where(user: user) }

  mount_uploader :pic, PicUploader


end

app/controllers/conf_rooms_controller.rb
class ConfRoomsController < ApplicationController
  before_action :set_conf_room, only: [:show, :edit, :update, :destroy]
  before_action :set_order_by, only: [:search, :index]

  def search
#    @conf_rooms = ConfRoom.for_user(current_user).where("description like ?", "%#{params[:search_query]}%").order(@order_by)
    @conf_rooms = current_user.campus.conf_rooms.where("description like ?", "%#{params[:search_query]}%").order(@order_by)
    render template: "conf_rooms/index"
  end

  # GET /conf_rooms
  # GET /conf_rooms.json
  def index
    @conf_rooms = current_user.campus.conf_rooms.order(@order_by)
    # @conf_rooms = ConfRoom.for_user(current_user)
  end

  # GET /conf_rooms/1
  # GET /conf_rooms/1.json
  def show
  end

  # GET /conf_rooms/new
  def new
    @conf_room = ConfRoom.new
  end

  # GET /conf_rooms/1/edit
  def edit
  end

  def add
  end

  # POST /conf_rooms
  # POST /conf_rooms.json
  def create
    @conf_room = ConfRoom.new(conf_room_params)
    @conf_room.user = current_user
    respond_to do |format|
      if @conf_room.save
        format.html { redirect_to @conf_room, notice: 'Conf room was successfully created.' }
        format.json { render :show, status: :created, location: @conf_room }
      else
        format.html { render :new }
        format.json { render json: @conf_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conf_rooms/1
  # PATCH/PUT /conf_rooms/1.json
  def update
    respond_to do |format|
      if @conf_room.update(conf_room_params)
        format.html { redirect_to @conf_room, notice: 'Conf room was successfully updated.' }
        format.json { render :show, status: :ok, location: @conf_room }
      else
        format.html { render :edit }
        format.json { render json: @conf_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conf_rooms/1
  # DELETE /conf_rooms/1.json
  def destroy
    @conf_room.destroy
    respond_to do |format|
      format.html { redirect_to conf_rooms_url, notice: 'Conf room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conf_room
 #     @conf_room = ConfRoom.for_user(current_user).find(params[:id])
      @conf_room = current_user.campus.conf_rooms.find(params[:id])
    end

    def set_order_by
      @order_by = params[:order_by]  || "name DESC, location DESC, sq_feet DESC, description DESC"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conf_room_params
      params.require(:conf_room).permit(:name, :location, :sq_feet, :description, :user_id, :pic, :campus_id, :remove_pic, :feature_ids => [])
    end
end

app/views/conf_rooms/_form.html.erb
<%= form_for(@conf_room) do |f| %>
  <% if @conf_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conf_room.errors.count, "error") %> prohibited this conf_room from being saved:</h2>

      <ul>
      <% @conf_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: 'control-label' %><br>
    <%= f.text_field :name, class: 'form-control', style: 'max-width:500px' %>
  </div>
  <div class="field">
    <%= f.label :location, class: 'control-label' %><br>
    <%= f.text_field :location, class: 'form-control', style: 'max-width:500px' %>
  </div>
  <div class="field">
    <%= f.label :sq_feet, class: 'control-label' %><br>
    <%= f.number_field :sq_feet, class: 'form-control', style: 'max-width:500px' %>
  </div>
  <div class="field">
    <%= f.label :description, class: 'control-label' %><br>
    <%= f.text_field :description, class: 'form-control', style: 'max-width:500px' %>
  </div>
  <div class="field">
    <%= f.label :campus_id, class: 'control-label' %><br>
    <%= f.text_field :campus_id, class: 'form-control', style: 'max-width:500px' %>
  </div>
  <div class="field has-success">
    <%= f.label :pic, class: 'control-label'%><br>
    <%= f.text_field :pic, class: 'form-control', style: 'max-width:500px' %><br>
    <%= f.file_field :pic %>
    <%= image_tag(@conf_room.pic_url) if @conf_room.pic? %>
  </div>
  <div>
    <label>
      <%= f.check_box :remove_pic %>
        Click to remove pic
    </label>
  </div>
  <div class="field">
      <%= hidden_field_tag "conf_room[feature_ids][]", nil %>
      <% Feature.all.each do |feature| %>
        <%= check_box_tag "conf_room[feature_ids][]", feature.id, @conf_room.feature_ids.include?(feature.id), id: dom_id(feature) %>
        <%= label_tag dom_id(feature), feature.feat %><br>
      <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conf_rooms/edit.html.erb
<h1>Edit your rooms here</h1>

<%= render 'form' %>

<%= link_to 'Show', @conf_room %> |
<%= link_to 'Back', conf_rooms_path %>

app/views/conf_rooms/index.html.erb
<center><h1><%= @current_user.name %>, here are the rooms at <%= @current_user.campus.name %></center>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Campus Rooms</h3>
    </div>
  </div>
  <!-- /.row -->
  <!-- Page Features -->
  <div class="row text-center">
    <% @conf_rooms.each do |conf_room| %>
        <div class="col-md-3 col-sm-6 hero-feature">
          <div class="thumbnail">
            <%= image_tag conf_room.pic_url %>
            <div class="caption">
              <h4><%= conf_room.name %></h4>
              <h5><%= conf_room.description %></h5>
              <div class="buttons">
                <p>
                <%= link_to new_feature_path, class: "btn btn-primary slide" do %>
                    <span class="glyphicon glyphicon-plus"></span> Add Features
                <% end %>
                </p>
              </div>
              <div class="buttons">
                <p>
                <%= link_to edit_conf_room_path(conf_room), class: "btn btn-primary slide" do %>
                    <span class="glyphicon glyphicon-edit"></span> Edit Rooms
                <% end %>
                </p>
              </div>
              <div class="buttons">
                <p>
                <%= link_to conf_room, class: "btn btn-primary slide" do %>
                    <span class="glyphicon glyphicon-eye-open"></span> Show Rooms
                <% end %>
                </p>
              </div>
              <div class="buttons">
                <p>
                <%= link_to new_reservation_path, class: "btn btn-primary slide" do %>
                    <span class="glyphicon glyphicon-plus-sign"></span> Reserve a Room
                <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <!-- /.row -->

  <hr>

  <%= link_to "Reservations", reservations_path %>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Ahmad Hutasuhut 2014</p>
      </div>
    </div>
  </footer>
</div>

app/views/conf_rooms/new.html.erb
<h1>Add your conference room here</h1>

<%= render 'form' %>

<%= link_to 'Back', conf_rooms_path %>

app/views/conf_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conf_room.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @conf_room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @conf_room.description %>
</p>

<p class="sq_feet" data-sqfootage="<%= @conf_room.sq_feet %>">
  <button class="show_feet">Click to show square footage</button>
</p>

<table class="table">
  <h2>Current Reservations for this Room</h2>
  <thead>
  <tr>
    <th> Starts At: </th>
    <th> Ends At: </th>
    <th> Notes: </th>
    <th> Event Title: </th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <% if @conf_room.reservations.present? %>

    <td> <%= @conf_room.reservations[0][:ends_at] %> </td>
    <td> <%= @conf_room.reservations[0][:notes] %> </td>
    <td> <%= @conf_room.reservations[0][:event_title] %> </td>
    <% end %>
  </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_conf_room_path(@conf_room) %> |
<%= link_to 'Back', conf_rooms_path %>