config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :campuses
  resources :reservations
  resources :users
  resources :features

  root 'welcome#index'

  resources :conf_rooms do
    collection do
      post "search"
    end
  end

  post "signin", to: "welcome#signin"
  delete "signout", to: "welcome#signout"

  get "signups", to: "signups#index"
  post "signups", to: "signups#signup"
  get 'tiy_rooms/index'

  get "reservations", to: "reservations#index"

end

app/views/layouts/_nav_tabs.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li role="presentation" class="expand"><%= link_to 'Home', root_path %></li>
          <% if signed_in? %>
            <li role="presentation" class="expand"><%= link_to 'Conference Rooms', conf_rooms_path %></li>
              <% if signed_in? && current_user.staff? %>
                <li role="presentation" class="expand"><%= link_to 'Users', users_path %></li>
              <% end %>
            <% end %>
        </ul>
        <% if signed_in? %>
          <%= form_tag search_conf_rooms_path, class: "navbar-form navbar-left"%>
            <div class="form-group">
              <%= text_field_tag "search_query", nil, class: "form-control", placeholder: "Search Room Descriptions" %>
            </div>
            <%= submit_tag "Search", class: "btn btn-default" %><br>
            <%= button_to "Reset", conf_rooms_path, class: "btn btn-warning" %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li role="presentation" ><%= button_to "Sign Out", signout_path, method: :delete, class: "btn btn-default navbar-btn" %></li>
          <% else %>
              <li role="presentation">
                <%= form_tag signin_path, class: "navbar-form navbar-left" do %>
                  <%= text_field_tag "email", nil, class: "form-control", placeholder: "Email"%>
                  <%= password_field_tag "password", nil, class: "form-control", placeholder: "Password" %>
                  <%= submit_tag "Sign In" %>
                <% end %>
              </li>
         <% end %>
        </ul>
      </div>
    </div>
</nav>
<br>
<br>
<br>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success"><strong><%= flash[:notice] %></strong>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
    </div>
<% end %>
<% if flash[:warning] %>
    <div class="alert alert-warning"><%= flash[:warning] %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TIYConfRoomsApp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


<%= render 'layouts/notices' %>
<%= render 'layouts/nav_tabs' %>
<br>
<br>

<%= yield %>

</body>
</html>